Pal 710 ecr push
gchq/Palisade-readers pull request #53
Opened 2020-09-02 19:35 UTC by ac74475

2020-09-03 10:13 UTC, developer01189998819991197253 commented on Jenkinsfile
> +                                    sh "mvn -s ${MAVEN_SETTINGS} org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar -Dsonar.projectKey=Palisade-Readers-${GIT_BRANCH_NAME} -Dsonar.proje
this doesnt work, just causes a project in sq called Palisade-Readers-

2020-09-03 10:14 UTC, developer01189998819991197253 requested changes
small change

2020-09-08 10:50 UTC, developer01189998819991197253 approved these changes

2020-09-08 13:47 UTC, pd104923 approved these changes

2020-09-09 14:29 UTC, pd104923 approved these changes

2020-09-10 09:55 UTC, developer01189998819991197253 approved these changes

2020-09-10 10:40 UTC, dev-958 approved these changes

2020-09-10 14:35 UTC, merged