Pal 414 resource service kafka update
gchq/Palisade-readers pull request #63
Opened 2020-11-10 15:33 UTC by pd104923

2020-11-11 10:57 UTC, developer01189998819991197253 requested changes

2020-11-11 10:57 UTC, developer01189998819991197253 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/util/FunctionalIterator.java
> +public interface FunctionalIterator<T> extends Iterator<T> {
Bit of Javadoc as to what this interface is used for might be useful

2020-11-11 10:57 UTC, developer01189998819991197253 commented on hadoop-resource/src/test/java/uk/gov/gchq/palisade/service/resource/util/FunctionalIteratorTest.java
> +@RunWith(JUnit4.class)
Does it have to be a Junit4 test?

2020-11-11 10:57 UTC, developer01189998819991197253 commented on hadoop-resource/src/test/java/uk/gov/gchq/palisade/service/resource/util/FunctionalIteratorTest.java
> +        assertEquals(listOf(dslTest), List.of(1, 2, 3, 4, 5, 6));
Can we move to assertThat over assertEquals

2020-11-11 17:51 UTC, developer01189998819991197253 requested changes
few small test changes
Update naming conventions
use AssertJ
Assert the Exception messages

2020-11-11 17:51 UTC, developer01189998819991197253 commented on hadoop-resource/src/test/java/uk/gov/gchq/palisade/service/resource/util/HadoopResourceDetailsTest.java
> +    }
Update tests to follow the correct naming convention
Add an assertion on the message returned from the thrown exception

```suggestion
    @Test
    void testNoTypeThrowsException() {
        // Given
        URI invalidType = new File(".").toURI().resolve("file.format");

        // When the resource is retrieved with an invalid format
        Exception illegalAccessException = assertThrows(IllegalArgumentException.class,
                () -> HadoopResourceDetails.getResourceDetailsFromFileName(invalidType), "Test should throw an exception");

        // Then check the assertion message
        assertThat(illegalAccessException.getMessage()).contains("Filename doesn't comply with TYPE_FILENAME.FORMAT");
    }
```

2020-11-11 17:51 UTC, developer01189998819991197253 commented on hadoop-resource/src/test/java/uk/gov/gchq/palisade/service/resource/service/HadoopResourceServiceTest.java
> +        assertFalse(success);
```suggestion
        assertThat(success).isFalse();
```

2020-11-11 17:51 UTC, developer01189998819991197253 commented on hadoop-resource/src/test/java/uk/gov/gchq/palisade/service/resource/service/HadoopResourceServiceTest.java
> +    void resourceDetailsGetDataServiceConnection() {
update tests with the right naming convention

2020-11-11 17:51 UTC, developer01189998819991197253 commented on hadoop-resource/src/test/java/uk/gov/gchq/palisade/service/resource/util/HadoopResourceDetailsTest.java
> +        assertFalse(details, "This should be false as the filename fullPath doesn't follow the pattern");
```suggestion
        assertThat(details).isFalse();
```

2020-11-12 08:34 UTC, pd104923 commented on hadoop-resource/src/test/java/uk/gov/gchq/palisade/service/resource/util/HadoopResourceDetailsTest.java
> +    }
Updated

2020-11-12 09:54 UTC, developer01189998819991197253 approved these changes

2020-11-16 06:49 UTC, kg981167224 reviewed
Couple of minor comments

2020-11-16 06:49 UTC, kg981167224 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/service/HadoopResourceService.java
>  import java.util.stream.Stream;
Remove Stream import and all references in comments?

2020-11-16 08:56 UTC, pd104923 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/service/HadoopResourceService.java
>  import java.util.stream.Stream;
Done

2020-11-16 09:08 UTC, kg981167224 submitted a review, later dismissed

2020-11-17 10:41 UTC, dev930018 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/util/FunctionalIterator.java
> +                return null;
I feel like this shouldn't return null in this case, but I don't know if throwing a runtime exception is any better...
I'm happy with the hasNext() catch returning false though, no issue there.

2020-11-17 10:41 UTC, dev930018 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/util/FunctionalIterator.java
> +public interface FunctionalIterator<T> extends Iterator<T> {
I'm unconvinced about this class being in readers, but equally it probably shouldn't be in common.
Something to think about when we're organising where service impls live

2020-11-17 12:34 UTC, pd104923 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/util/FunctionalIterator.java
> +                return null;
If the next is called then it is not likely to get to the `catch` code as a `false` return on the `hasNext` call will mean that this method should not be called.

2020-11-17 12:36 UTC, pd104923 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/util/FunctionalIterator.java
> +public interface FunctionalIterator<T> extends Iterator<T> {
I was trying to prevent any additions to the common library but, as you mentioned, this will need to be thought out properly at some point.

2020-11-17 13:30 UTC, dev930018 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/util/FunctionalIterator.java
> +                return null;
Should possibly throw the correct iterator exception then (NoSuchElementException?)

2020-11-17 13:32 UTC, dev930018 requested changes

2020-11-17 13:32 UTC, dev930018 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/util/FunctionalIterator.java
> +                return null;
```suggestion
                throw new NoSuchElementException("RemoteIterator threw IOException: " + ex.getMessage());
```

2020-11-17 13:57 UTC, dev930018 submitted a review, later dismissed

2020-11-17 14:37 UTC, dev930018 approved these changes

2020-11-23 11:18 UTC, merged