Pal 974 passthrough rule for data service
gchq/Palisade-readers pull request #65
Opened 2021-03-02 17:45 UTC by m78233

2021-03-03 11:45 UTC, kg981167224 requested changes

2021-03-03 11:45 UTC, kg981167224 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java
> +                recordsProcessed.set(-1L);
I can't see anywhere explaining what -1 means for records processed. I assume it's only every used for a passthrough rule?

2021-03-03 13:02 UTC, m78233 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java
> +                recordsProcessed.set(-1L);
It is a convention.   The number -1 will indicate that we are bypassing the deserialising/serialise.  But point taken,  it is a magic number and should be documented at least with a comment

2021-03-03 13:48 UTC, kg981167224 approved these changes

2021-03-03 14:24 UTC, dev930018 requested changes

2021-03-03 14:24 UTC, dev930018 commented on readers-common/src/test/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriterTest.java
> +                .addRule("sec ond", new TestPassThroughRule<>())
```suggestion
                .addRule("second", new TestPassThroughRule<>())
```

2021-03-03 14:24 UTC, dev930018 commented on readers-common/src/test/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriterTest.java
> +                .isEqualTo((new AtomicLong(3L)).longValue());
```suggestion
                .isEqualTo(3L);
```

2021-03-03 14:24 UTC, dev930018 commented on readers-common/src/test/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriterTest.java
> +                .isEqualTo((new AtomicLong(3L)).longValue());
```suggestion
                .isEqualTo(3L);
```

2021-03-03 14:24 UTC, dev930018 commented on readers-common/src/test/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriterTest.java
> +                .isEqualTo((new AtomicLong(-1L)).longValue());
```suggestion
                .isEqualTo(-1L);
```

2021-03-03 14:24 UTC, dev930018 commented on readers-common/src/test/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriterTest.java
> +                .isEqualTo((new AtomicLong(-1L)).longValue());
```suggestion
                .isEqualTo(-1L);
```

2021-03-03 14:59 UTC, dev930018 reviewed
Perhaps a little more in the way of documentation?

2021-03-03 14:59 UTC, dev930018 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java
> +        return applicableRule.isPresent();
```suggestion
        // No need to consider the case where the rules list is empty as this is disallowed by the policy-service
        return rules.getRules().values()
                .stream()
                .anyMatch(rule -> rule.isApplicable(user, context))
```

2021-03-03 14:59 UTC, dev930018 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java
> +
```suggestion
    /**
     * Rules must be applied to the records in a resource if any single rule must be applied.
     * Otherwise, application of rules and de/serialisation can be skipped.
     */
```

2021-03-03 15:03 UTC, dbz120896 approved these changes

2021-03-04 08:27 UTC, dbz120896 approved these changes

2021-03-04 08:49 UTC, kg981167224 approved these changes

2021-03-04 14:41 UTC, dev930018 commented
Missing some extra javadoc
```
[2021-03-03T15:39:56.873Z] [ERROR] /home/jenkins/agent/workspace/Palisade-readers_PR-65/Palisade-readers/readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java:156: Expected @return tag. [JavadocMethod]

[2021-03-03T15:39:56.873Z] [ERROR] /home/jenkins/agent/workspace/Palisade-readers_PR-65/Palisade-readers/readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java:156:49: Expected @param tag for 'rules'. [JavadocMethod]

[2021-03-03T15:39:56.873Z] [ERROR] /home/jenkins/agent/workspace/Palisade-readers_PR-65/Palisade-readers/readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java:156:67: Expected @param tag for 'user'. [JavadocMethod]

[2021-03-03T15:39:56.873Z] [ERROR] /home/jenkins/agent/workspace/Palisade-readers_PR-65/Palisade-readers/readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java:156:87: Expected @param tag for 'context'. [JavadocMethod]

[2021-03-03T15:39:56.873Z] Audit done.
```

2021-03-04 14:47 UTC, dev930018 requested changes
Some missing fields for javadoc

2021-03-04 14:47 UTC, dev930018 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java
> +     */
```suggestion
     * Otherwise, application of rules and de/serialisation can be skipped.
     * 
     * @param rules   a collection of rules to check
     * @param user    the user who made the request, passed to each {@code Rule#isApplicable} method
     * @param context the context of the request, passed to each {@code Rule#isApplicable} method
     * @return whether the rules need to be applied to the resource, false if all of them may be skipped
     * @apiNote if this returns false, the resource will not be de/serialised into records, improving performance
     */
```

2021-03-04 15:13 UTC, dev930018 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java
> +     *
```suggestion
     *
```

2021-03-04 15:18 UTC, dev930018 approved these changes

2021-03-04 15:18 UTC, merged