PAL-506-Readers-remove-unused-dependencies: pom files with dependenci…
gchq/Palisade-readers pull request #66
Opened 2021-03-10 15:36 UTC by m78233

…es removed.

Signed-off-by: m78233 <61839550+m78233@users.noreply.github.com>

2021-03-11 09:23 UTC, pd104923 requested changes
One minor tweak

2021-03-11 09:23 UTC, pd104923 commented on hadoop-reader/pom.xml
> +        <!-- User, Resource, Context types -->
I think this needs to be re-worded as `readers-common` doesn't contain these "things". Readers-common contains the readers, writers and the requests objects.

2021-03-11 09:30 UTC, m78233 commented on hadoop-reader/pom.xml
> +        <!-- User, Resource, Context types -->
Yes,  changed to Readers, Request and Response

2021-03-11 09:34 UTC, pd104923 approved these changes

2021-03-11 10:39 UTC, developer01189998819991197253 requested changes

2021-03-11 10:39 UTC, developer01189998819991197253 commented on hadoop-reader/pom.xml
> +        <!-- JUnit 4 test framework -->
Can just replace with
```suggestion
        <!-- Testing Dependency -->
```
Saves us having to update it when we update it to junit 5

2021-03-11 10:39 UTC, developer01189998819991197253 commented on hadoop-resource/pom.xml
> +        <!-- JUnit 5 test framework -->
same here, just change it to "Testing Dependency"

2021-03-11 10:51 UTC, m78233 commented on hadoop-resource/pom.xml
> +        <!-- JUnit 5 test framework -->
done

2021-03-11 11:01 UTC, developer01189998819991197253 approved these changes

2021-03-11 11:08 UTC, pd104923 submitted a review, later dismissed

2021-03-11 13:36 UTC, dev930018 reviewed
I'd like to see a build of services with these changes - I remember hadoop being quite finicky

2021-03-11 14:34 UTC, dev930018 requested changes
Some preliminary local changes suggest something like:
```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    licenses/bsd_license_3.html
	deleted:    licenses/mit_license.html
	deleted:    shade-hadoop-client/README.md
	deleted:    shade-hadoop-client/mvn_dependency_tree.txt
	deleted:    shade-hadoop-client/pom.xml

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   NOTICES.md
	modified:   hadoop-reader/mvn_dependency_tree.txt
	modified:   hadoop-reader/pom.xml
	modified:   hadoop-reader/src/main/java/uk/gov/gchq/palisade/reader/HadoopDataReader.java
	modified:   hadoop-resource/mvn_dependency_tree.txt
	modified:   hadoop-resource/pom.xml
	modified:   pom.xml
	modified:   readers-common/mvn_dependency_tree.txt
	modified:   readers-common/pom.xml
	modified:   readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisedDataReader.java
	modified:   readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	licenses/eclipse public license v2.0 - epl-v20.html
```
So some license updates to do also

2021-03-11 14:34 UTC, dev930018 commented on hadoop-reader/pom.xml
> +        <!-- Readers, Request & Response types -->
Could be styled more like services are, but not too big an issue

2021-03-11 14:34 UTC, dev930018 commented on hadoop-reader/pom.xml
>          </dependency>
We can remove this (and the jackson annotations) as we no longer have a need to serialise the reader object

2021-03-11 14:34 UTC, dev930018 commented on hadoop-reader/pom.xml
>                  </exclusion>
Hadoop resource service also excludes slf4j-log4j - could we add that for consistency? (It is sometimes needed to be excluded)

2021-03-11 14:34 UTC, dev930018 commented on hadoop-reader/pom.xml
>          </dependency>
Is there a ticket for junit5 stuff?

2021-03-11 14:34 UTC, dev930018 commented on hadoop-reader/pom.xml
> +        <!-- Hadoop framework -->
These comments could be better

2021-03-11 14:34 UTC, dev930018 commented on hadoop-resource/pom.xml
>      </properties>
properties should be after artifactId and url

2021-03-11 14:34 UTC, dev930018 commented on hadoop-resource/pom.xml
> +        <!-- Testing Dependency -->
Again, descriptions and style could be improved

2021-03-11 14:34 UTC, dev930018 commented on pom.xml
> +
This won't be needed

2021-03-11 14:34 UTC, dev930018 commented on pom.xml
> +        <!-- Dependency properties -->
These are better described as Properties, but nothing to do with dependencies

2021-03-11 14:34 UTC, dev930018 commented on pom.xml
>          <failsafe.version>2.22.1</failsafe.version>
The failsafe version and plugin are redundant here

2021-03-11 14:34 UTC, dev930018 commented on pom.xml
>      <properties>
I can't comment directly, but it looks like the shade-hadoop-client is now redundant and can be deleted

2021-03-11 14:34 UTC, dev930018 commented on shade-hadoop-client/pom.xml
>      <properties>
This whole module can be deleted

2021-03-11 14:34 UTC, dev930018 commented on readers-common/pom.xml
> +            <version>${jackson.version}</version>
Not needed, just drop the jackson annotations, we don't need to serialise this stuff

2021-03-11 15:20 UTC, m78233 commented on hadoop-reader/pom.xml
> +        <!-- Readers, Request & Response types -->
changed style to be in-line with services

2021-03-11 15:23 UTC, m78233 commented on hadoop-reader/pom.xml
> +        <!-- Hadoop framework -->
Reads "Hadoop config classes" now

2021-03-11 15:28 UTC, m78233 commented on hadoop-reader/pom.xml
>                  </exclusion>
added the exclusion for slf4j-log4j12  but also note i have left the original exclusion for log4j as I assume we still want to exclude this as well

2021-03-11 15:31 UTC, m78233 commented on hadoop-reader/pom.xml
>          </dependency>
Yes, PAL-767 is in the backlog

2021-03-11 15:35 UTC, m78233 commented on hadoop-resource/pom.xml
>      </properties>
done

2021-03-11 15:35 UTC, m78233 commented on hadoop-resource/pom.xml
> +        <!-- Testing Dependency -->
done

2021-03-11 15:38 UTC, m78233 commented on pom.xml
>      <properties>
removed it

2021-03-11 15:40 UTC, m78233 commented on pom.xml
> +        <!-- Dependency properties -->
Changed convention to the same used in services

2021-03-11 15:43 UTC, m78233 commented on pom.xml
> +
done

2021-03-11 16:10 UTC, m78233 commented on pom.xml
>          <failsafe.version>2.22.1</failsafe.version>
removed both

2021-03-11 16:11 UTC, m78233 commented on readers-common/pom.xml
> +            <version>${jackson.version}</version>
done

2021-03-11 16:13 UTC, m78233 commented on shade-hadoop-client/pom.xml
>      <properties>
done

2021-03-15 11:12 UTC, dev930018 commented on pom.xml
> -            </plugin>
I believe we should be keeping surefire as it's still relevant (we're still doing unit-tests)

2021-03-15 11:12 UTC, dev930018 commented on hadoop-reader/pom.xml
>          </dependency>
Nope, because the annotations are used, but unneccesarily.

2021-03-15 11:22 UTC, dev930018 requested changes

2021-03-15 11:22 UTC, dev930018 commented on readers-common/pom.xml
>      <url>https://github.com/gchq/Palisade-readers/tree/develop/readers-common</url>
Once surefire-plugin has been re-added, I've noticed readers-common has `src/test/uk...` - this should be moved to `src/test/java/uk...`

2021-03-15 16:37 UTC, m78233 commented on pom.xml
> -            </plugin>
yes, put it back in

2021-03-15 16:38 UTC, m78233 commented on readers-common/pom.xml
>      <url>https://github.com/gchq/Palisade-readers/tree/develop/readers-common</url>
refactored to have java directory at the base

2021-03-15 16:50 UTC, dev930018 requested changes
One final thing - there's still a couple of unneccessary (and now not-depended-upon) jackson-annotations bits lying around in HadoopResourceService, HadoopDataReader and SerialisedDataReader. These should be deleted.

2021-03-16 16:13 UTC, dev930018 requested changes

2021-03-16 16:13 UTC, dev930018 commented on pom.xml
>              </plugin>
Failsafe plugin should be deleted if we have no component/contract tests

2021-03-17 13:06 UTC, dev930018 approved these changes

2021-03-17 13:06 UTC, merged