Pal 884 palisade readers update documentation
gchq/Palisade-readers pull request #67
Opened 2021-03-24 13:49 UTC by m78233

2021-03-26 09:36 UTC, pd104923 requested changes
A few comments and suggestions

2021-03-26 09:36 UTC, pd104923 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/service/HadoopResourceService.java
> +     * a resource and allows Palisade to provide policy controlled access to it via the other methods in this interface.
```suggestion
     * to a resource and allows Palisade to provide policy controlled access to it via the other methods in this interface.
```

2021-03-26 09:36 UTC, pd104923 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisedDataReader.java
> + * and then de-serialises the data to the format the client is expecting.
```suggestion
 * and then deserialises the data to the format the client is expecting.
```

2021-03-26 09:36 UTC, pd104923 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java
> +     * Check to see if there is at least one rule that is applicable.  Rules
```suggestion
     * Check to see if there is at least one rule that is applicable. Rules
```

2021-03-26 09:36 UTC, pd104923 commented on README.md
> +data.  The Reader library provides the functionality for the Data Service to
```suggestion
request. This is then used to send a request to the Data Service to retrieve
the data. The Reader library provides the functionality for the Data Service to

```

2021-03-26 09:36 UTC, pd104923 commented on README.md
> +### Readers
I feel like this should be something like "Data Readers" rather than just `Readers`

2021-03-26 09:36 UTC, pd104923 commented on README.md
> +
I think that this can be removed as it is covered in more detail within the services repo. Plus the link to the binaries no longer exists

2021-03-26 09:36 UTC, pd104923 commented on README.md
> +`ResponseWriter`; and `DataReader`. These provide the basis of the solution
```suggestion
In terms of code, there are two interface that are core to this library, the
`ResponseWriter` and the `DataReader`. These provide the basis of the solution

```

2021-03-26 09:36 UTC, pd104923 commented on README.md
> +filtering.  This is used to set up a processing stream for the client's request.
```suggestion
first retrieve the references to the data plus the rules that will be used for
filtering. This is used to set up a processing stream for the client's request.

```

2021-03-26 09:36 UTC, pd104923 commented on README.md
> +implementation for the data retrieval. In the
This reads like the writer and reader classes are geared up for implementing Hadoop. While including Hadoop is a valid idea I think it needs to be separated from the other classes.
```suggestion
The writer in the class `SerialisingResponseWriter` and the reader
implementation in the abstract class `SerialisedDataReader` provide the
implementation for the data retrieval. The class `HadoopDataReader`
is the reader implementation for Hadoop. In the
```

2021-03-26 10:30 UTC, m78233 commented on README.md
> +### Readers
How about Palisade Readers

2021-03-26 11:08 UTC, pd104923 commented on README.md
> +### Readers
This is probably the better title

2021-03-26 12:00 UTC, m78233 commented on README.md
> +
Some reason, I did not see this the first time I went though the comments.  Yes, this has been deleted.

2021-03-30 07:18 UTC, pd104923 requested changes
A few minor updates to the ReadMe

2021-03-30 07:18 UTC, pd104923 commented on README.md
Remove this extra line break

2021-03-30 07:18 UTC, pd104923 commented on README.md
> +In terms of code, there are two interface that are core to this library, the
```suggestion
In terms of code, there are two interfaces that are core to this library, the

```

2021-03-30 07:18 UTC, pd104923 commented on README.md
Remove this extra line break

2021-03-30 07:18 UTC, pd104923 commented on README.md
> +deserialised into records where the rules are applied to filter the records.
```suggestion
The process will retrieve the data as an input stream. It will then be
deserialised into records where the rules are applied to redact or mask the records.
```

2021-03-30 07:56 UTC, m78233 commented on README.md
done

2021-03-30 07:57 UTC, m78233 commented on README.md
done

2021-03-30 11:32 UTC, dev930018 requested changes

2021-03-30 11:32 UTC, dev930018 commented on README.md
> +defined by the rules in place for the data.
Standard for Markdown *should* be semantic breaks - one-line-per-unit-of-thought - but it's a bit much.
Palisade docs in general have been using one-line-per-sentence though.

2021-03-30 11:32 UTC, dev930018 commented on README.md
> +```
Reference the file rather than quote the code

2021-03-30 11:32 UTC, dev930018 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/service/HadoopResourceService.java
> + * through the filing system.
I'd keep one of these, or re-word.
"should be added to the backing hadoop filesystem" would fit well enough

2021-03-30 11:32 UTC, dev930018 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisedDataReader.java
>   * need to implement a DataService for
```suggestion
 * need to implement a DataReader for
```
also look at the newlines in this bit of javadoc

2021-03-30 11:32 UTC, dev930018 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/request/DataReaderRequest.java
> + * the Attribute Masking Service and retrieved by the Data Service.
```suggestion
 * the Attribute-Masking Service and retrieved by the Data Service.
```

2021-03-30 11:32 UTC, dev930018 commented on readers-common/src/test/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriterTest.java
> +        String outputString = outputStream.toString();
I thought this would return something like `OutputStream[.....aklsfl....]` rather than `some file data \n some more file data`?

2021-03-30 11:37 UTC, dev930018 commented on README.md
> +defined by the rules in place for the data.
Reason being how prose and semantic writing works with git.
If i stick a big long sentence on the first line, then reformat it like this, every line thereafter changes.
You'll get more useful behaviour out of git if you write your prose like it's code - split discrete 'units' over separate lines

2021-03-30 11:53 UTC, m78233 commented on README.md
> +defined by the rules in place for the data.
I like being able to read the text in the editor, but yes the chopping and gluing together text is a downside.  I'll change to  the convention of a sentence per line.

2021-03-30 13:56 UTC, m78233 commented on README.md
> +```
Replaced the code with links to the code and followed on with the logical extension of that by changing names of the files with links.

2021-03-30 14:32 UTC, m78233 commented on readers-common/src/test/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriterTest.java
> +        String outputString = outputStream.toString();
The change was to simplify something I had written before.  As for the test, it is to verify that if there is at least one rule in a set of rules that should be applied, then the rules will be applied.    The applying of the rules did not require any changes so the content of input steam and output stream will be the same.  The key difference is that the input stream had three records delineated by the new line character.  Applying the rules will mean that the stream will be serialised, then deserialised and this will be reflected in the records processed and records returned.  Does that answer your question?

2021-04-12 13:22 UTC, pd104923 requested changes
A couple of comments.

2021-04-12 13:22 UTC, pd104923 commented on README.md
> +[SerialisingResponseWriter.write](readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java)` method, these classes are used to
```suggestion
[SerialisingResponseWriter.write](readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java) method, these classes are used to

```

2021-04-12 13:22 UTC, pd104923 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java
>               */
Can this needs to be changed to in-line comments rather than a dangling JavaDoc block
```
// If none of the rules apply, then just copy the bytes across.
// The value -1L is a convention to indicate deserialise/serialise is by-passed and the number of records
// processed and number of records returned will not be counted.
```

2021-04-12 13:22 UTC, pd104923 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisedDataReader.java
> + * and then deserialises the data to the format the client is expecting.
I think this is meant to be the other way round. We deserialise, from avro for example, so that we can apply rules to mask/redact the information and then serialise back when passing to the client.
```suggestion
 * This class is an abstract implementation of the {@link DataReader} which
 * deserialises the data into the format needed for applying the rules
 * and then serialises the data to the format the client is expecting.
```
It might be worth checking this though as I might be wrong.

2021-04-12 15:28 UTC, m78233 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisedDataReader.java
> + * and then deserialises the data to the format the client is expecting.
Yep, you got it right. Serialisation will convert a Java into a stream of bytes.  Deserialisation will convert a stream of bytes into an Object.

2021-04-12 15:42 UTC, pd104923 requested changes

2021-04-12 15:42 UTC, pd104923 commented on README.md
> +first retrieve the references to the data plus the rules that will be used for
There are a couple of returns before this line which means it's now a new paragraph within the ReadMe. I would remove at least 1 of these so that it reads properly from line 35.

2021-04-12 15:42 UTC, pd104923 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java
>               */
Is there a reason this wasn't applied/considered?

2021-04-12 15:50 UTC, m78233 commented on readers-common/src/main/java/uk/gov/gchq/palisade/reader/common/SerialisingResponseWriter.java
>               */
Thought that I had changed it.  Did it now.

2021-04-12 16:01 UTC, m78233 commented on README.md
> +first retrieve the references to the data plus the rules that will be used for
Changed format to the convention of one sentence per line.

2021-04-13 07:23 UTC, pd104923 submitted a review, later dismissed

2021-04-13 09:42 UTC, dev930018 reviewed
Happy with the content, but on the premise it's going to be moved about with removal of common and inversion of dependency between services and readers.

2021-04-30 09:31 UTC, pd104923 requested changes
One minor change

2021-04-30 09:31 UTC, pd104923 commented on README.md
> +`SerialisingResponseWriter` will then deserialise the stream into records where the rules are applied to redact or mask the records.
```suggestion
The `SerialisingResponseWriter` will then deserialise the stream into records where the rules are applied to redact or mask the records.

```

2021-04-30 11:01 UTC, pd104923 submitted a review, later dismissed

2021-05-05 15:28 UTC, dev930018 commented
Pom dependency on services needs to use `services.revision`

2021-05-07 09:47 UTC, dev930018 approved these changes

2021-05-07 09:48 UTC, merged