Pal 999 keep common library
gchq/Palisade-readers pull request #70
Opened 2021-04-20 09:52 UTC by dev930018

2021-04-20 10:33 UTC, developer01189998819991197253 reviewed
revert licenses but otherwise approved

2021-04-20 10:33 UTC, developer01189998819991197253 commented on Jenkinsfile
> +@Library('jenkinsfile-lib@feature/PAL-999-keep-common-library')_
revert jenkinsfile before merge

2021-04-20 11:47 UTC, pd104923 requested changes

2021-04-20 11:47 UTC, pd104923 commented on hadoop-reader/src/main/java/uk/gov/gchq/palisade/service/data/hadoop/HadoopDataReader.java
> +    public HadoopDataReader(final Configuration configuration) throws IOException {
Does this need some JavaDoc?

2021-04-20 11:47 UTC, pd104923 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/hadoop/HadoopConfiguration.java
> +public class HadoopConfiguration {
This class will need JavaDoc

2021-04-20 11:47 UTC, pd104923 commented on hadoop-reader/src/main/java/uk/gov/gchq/palisade/service/data/hadoop/HadoopConfiguration.java
> +public class HadoopConfiguration {
This class will need some JavaDoc

2021-04-20 11:59 UTC, developer01189998819991197253 commented on hadoop-reader/src/main/java/uk/gov/gchq/palisade/service/data/hadoop/HadoopDataReader.java
> +    public HadoopDataReader(final Configuration configuration) throws IOException {
added

2021-04-20 12:04 UTC, developer01189998819991197253 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/hadoop/HadoopConfiguration.java
> +public class HadoopConfiguration {
added

2021-04-20 12:04 UTC, developer01189998819991197253 commented on hadoop-reader/src/main/java/uk/gov/gchq/palisade/service/data/hadoop/HadoopConfiguration.java
> +public class HadoopConfiguration {
added

2021-04-20 12:16 UTC, pd104923 requested changes

2021-04-20 12:16 UTC, pd104923 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/hadoop/HadoopConfiguration.java
> + * A Spring Hadoop Configuration class, creating the necessary beans for a Hadoop data reader
```suggestion
 * A Spring Hadoop Configuration class, creating the necessary beans for a Hadoop resource service
```

2021-04-20 12:17 UTC, pd104923 approved these changes

2021-04-22 10:07 UTC, ac74475 commented
can be merged once corresponding palisade services PR is merged

2021-04-27 15:11 UTC, dev930018 commented on hadoop-reader/src/main/java/uk/gov/gchq/palisade/service/data/hadoop/HadoopConfiguration.java
> +    @ConditionalOnProperty(prefix = "data", name = "implementation", havingValue = "hadoop", matchIfMissing = true)
```suggestion
    @ConditionalOnProperty(prefix = "data", name = "implementation", havingValue = "hadoop")
```
Simple/default/null should matchifmissing, not this

2021-04-27 15:11 UTC, dev930018 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/hadoop/HadoopResourceDetails.java
> +/*
Check line-endings are reasonable considering this diff

2021-04-28 07:08 UTC, pd104923 commented on hadoop-reader/src/main/java/uk/gov/gchq/palisade/service/data/hadoop/HadoopConfiguration.java
> +    @ConditionalOnProperty(prefix = "data", name = "implementation", havingValue = "hadoop", matchIfMissing = true)
Removed the "matchIfMissing"

2021-04-28 07:32 UTC, pd104923 commented on hadoop-resource/src/main/java/uk/gov/gchq/palisade/service/resource/hadoop/HadoopResourceDetails.java
> +/*
The line endings look good.

2021-04-28 11:40 UTC, developer01189998819991197253 requested changes

2021-04-28 11:40 UTC, developer01189998819991197253 commented on NOTICES.md
> +* data-service ([uk.gov.gchq.palisade:data-service:0.5.0-SNAPSHOT](no url defined))
add data service url to the notices, like done for the resource service

2021-04-28 11:40 UTC, developer01189998819991197253 commented on licenses/bsd_license_3.html
> -<!DOCTYPE html>
revert licence changes

2021-04-28 12:09 UTC, pd104923 commented on NOTICES.md
> +* data-service ([uk.gov.gchq.palisade:data-service:0.5.0-SNAPSHOT](no url defined))
url added

2021-04-28 12:32 UTC, developer01189998819991197253 approved these changes

2021-04-28 16:38 UTC, merged