Pal 1021 s3 resource service
gchq/Palisade-readers pull request #77
Opened 2021-05-11 16:58 UTC by developer01189998819991197253

2021-05-12 09:16 UTC, pd104923 requested changes
A few suggestions and questions.

2021-05-12 09:16 UTC, pd104923 commented on s3-resource/src/test/java/uk/gov/gchq/palisade/service/resource/s3/util/S3ResourceBuilderTest.java
> +                .as("Check that when building a resource with a s3 prefix, it is an instance of a S3Resource")
```suggestion
                .as("Check that when building a resource with an s3 prefix, it is an instance of an S3Resource")
```

2021-05-13 11:03 UTC, pd104923 approved these changes

2021-05-14 10:22 UTC, dev930018 requested changes
Mostly just check dependencies

2021-05-14 10:22 UTC, dev930018 commented on hadoop-reader/pom.xml
> +        </dependency>
Double-check this works, i remember something very awkward about getting hadoop's gson to work with spring

2021-05-14 10:22 UTC, dev930018 commented on hadoop-reader/src/main/java/uk/gov/gchq/palisade/service/data/hadoop/HadoopConfiguration.java
> +    @ConditionalOnProperty(prefix = "data", name = "implementation", havingValue = "hadoop", matchIfMissing = true)
```suggestion
    @ConditionalOnProperty(prefix = "data", name = "implementation", havingValue = "hadoop")
```
I think you want the default reader if this config key is not set

2021-05-14 10:22 UTC, dev930018 commented on hadoop-resource/pom.xml
> +        </dependency>
Again, double-check

2021-05-14 10:22 UTC, dev930018 commented on hadoop-resource/src/test/java/uk/gov/gchq/palisade/service/resource/hadoop/HadoopResourceServiceComponentTest.java
> +                .hasToString(parent1.getId());
Why not isEqualTo?

2021-05-14 10:22 UTC, dev930018 commented on s3-resource/pom.xml
> +        </dependency>
Not needed
```suggestion
```

2021-05-14 10:22 UTC, dev930018 commented on s3-resource/pom.xml
> +        </dependency>
Test dependency?

2021-05-14 10:22 UTC, dev930018 commented on s3-resource/pom.xml
> +        </dependency>
Also, why not the specific S3 artifact?

2021-05-14 10:22 UTC, dev930018 commented on s3-resource/pom.xml
> +        </dependency>
Ditto test deps and s3-specific artifact.
Also, while i found a v1 and a v2 were needed, I didn't see a need for any more (2 deps total, not 3)

2021-05-14 10:22 UTC, dev930018 commented on s3-resource/pom.xml
> +        </dependency>
Since resource-service is a provided dep, and that has jackson databind, is this needed?

2021-05-14 10:22 UTC, dev930018 commented on s3-resource/pom.xml
> +        </dependency>
Definitely not needed, prefer spring NotNulls

2021-05-14 10:22 UTC, dev930018 commented on s3-resource/pom.xml
> +        </dependency>
Again, possibly not needed given the resource-service dep

2021-05-14 10:22 UTC, dev930018 commented on s3-resource/pom.xml
> +        </dependency>
Not needed, junit-jupiter comes with spring-boot-starter-test

2021-05-14 10:22 UTC, dev930018 commented on s3-resource/pom.xml
> +            <artifactId>akka-stream-alpakka-s3_2.13</artifactId>
parameterise scala-version

2021-05-14 10:22 UTC, dev930018 commented on s3-resource/src/main/java/uk/gov/gchq/palisade/service/resource/s3/S3ResourceService.java
> +     * Check the resource exists in the bucket by calling {@link S3#listBucket(String, Optional)}, if it does, then get the objectMetadata by calling {@link S3#getObjectMetadata(String, String)}.
Quite a long line - break somewhere?

2021-05-14 11:16 UTC, developer01189998819991197253 commented on hadoop-resource/src/test/java/uk/gov/gchq/palisade/service/resource/hadoop/HadoopResourceServiceComponentTest.java
> +                .hasToString(parent1.getId());
Small update, forgot to remove the .toString

Basically, hasToString removes the need for .toString() 
So either you do
``assertThat(dir.resolve("folder1/folder2/"))
                .as("Check the URI of the parent is the correct URI")
                .hasToString(parent1.getId());
```
or
```
assertThat(dir.resolve("folder1/folder2/").toString())
                .as("Check the URI of the parent is the correct URI")
                .isEqualTo(parent1.getId());
```

2021-05-14 11:19 UTC, developer01189998819991197253 commented on hadoop-resource/pom.xml
> +        </dependency>
Seems to be working so far, tests pass, no compile issues

2021-05-14 11:19 UTC, developer01189998819991197253 commented on hadoop-resource/src/test/java/uk/gov/gchq/palisade/service/resource/hadoop/HadoopResourceServiceComponentTest.java
> +                .hasToString(parent1.getId());
Small update, forgot to remove the .toString

Basically, hasToString removes the need for .toString() 
So either you do
```
assertThat(dir.resolve("folder1/folder2/"))
                .as("Check the URI of the parent is the correct URI")
                .hasToString(parent1.getId());
```
or
```
assertThat(dir.resolve("folder1/folder2/").toString())
                .as("Check the URI of the parent is the correct URI")
                .isEqualTo(parent1.getId());
```

2021-05-14 11:20 UTC, developer01189998819991197253 commented on s3-resource/pom.xml
> +        </dependency>
seems to be the minimum needed for the tests to pass

2021-05-14 11:20 UTC, developer01189998819991197253 commented on s3-resource/pom.xml
> +        </dependency>
removed

2021-05-14 11:23 UTC, developer01189998819991197253 commented on hadoop-reader/pom.xml
> +        </dependency>
Seems to be working so far, tests pass, no compile issues

2021-05-14 12:00 UTC, developer01189998819991197253 commented on s3-resource/pom.xml
> +        </dependency>
I removed each dependency and tested individually and it looks like all 3 dependencies are required here

2021-05-14 12:05 UTC, developer01189998819991197253 commented on s3-resource/pom.xml
> +        </dependency>
the S3Client, and plenty of other test code, seems to be part of the aws java sdk dependency, and not included in aws-java-sdk-s3

2021-05-14 12:37 UTC, dev930018 commented on s3-resource/pom.xml
> +        </dependency>
S3 Data Reader had tests passing with:
```
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>${aws.s3.v1.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
            <version>${aws.s3.v2.version}</version>
            <scope>test</scope>
        </dependency>
 ```

2021-05-14 12:47 UTC, developer01189998819991197253 commented on s3-resource/pom.xml
> +        </dependency>
updated

2021-05-14 12:49 UTC, dev930018 approved these changes

2021-05-14 12:50 UTC, dev930018 commented
On-hold pending jenkinsfile, common, services merge

2021-05-18 13:19 UTC, dev930018 requested changes

2021-05-18 13:19 UTC, dev930018 commented on s3-resource/pom.xml
> +        <akka-stream-alpakka-parameter>s3_2.13</akka-stream-alpakka-parameter>
```suggestion
        <scala.version>2.13</scala.version>
```

2021-05-18 13:19 UTC, dev930018 commented on s3-resource/pom.xml
> +        <localstack.version>1.15.3</localstack.version>
```suggestion

        <!-- Test dependency versions -->
        <aws.s3.v1.version>1.11.1016</aws.s3.v1.version>
        <aws.s3.v2.version>2.16.60</aws.s3.v2.version>
        <spring-boot-testing.version>2.3.1.RELEASE</spring-boot-testing.version>
        <localstack.version>1.15.3</localstack.version>
```

2021-05-18 13:19 UTC, dev930018 commented on s3-resource/pom.xml
> +       -->
```suggestion

        <!--
       ~ Test Dependencies
       -->
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>${aws.s3.v1.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
            <version>${aws.s3.v2.version}</version>
            <scope>test</scope>
        </dependency>
```

2021-05-18 13:19 UTC, dev930018 commented on s3-resource/pom.xml
> +            <artifactId>akka-stream-alpakka-${akka-stream-alpakka-parameter}</artifactId>
```suggestion
            <artifactId>akka-stream-alpakka-s3_${scala.version}</artifactId>
```

2021-05-18 13:19 UTC, dev930018 commented on s3-resource/src/main/java/uk/gov/gchq/palisade/service/resource/s3/S3Configuration.java
> +import akka.stream.Materializer;
```suggestion
import akka.stream.Materializer;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
```

2021-05-18 13:19 UTC, dev930018 commented on s3-resource/src/main/java/uk/gov/gchq/palisade/service/resource/s3/S3Configuration.java
> +@EnableConfigurationProperties(S3Properties.class)
```suggestion
@ConditionalOnClass(ResourceService.class)
@EnableConfigurationProperties(S3Properties.class)
```

2021-05-18 13:19 UTC, dev930018 commented on s3-resource/src/main/resources/META-INF/spring.factories
> +org.springframework.boot.autoconfigure.EnableAutoConfiguration=uk.gov.gchq.palisade.service.data.s3.S3Configuration
```suggestion
org.springframework.boot.autoconfigure.EnableAutoConfiguration=uk.gov.gchq.palisade.service.resource.s3.S3Configuration
```

2021-05-18 16:45 UTC, dev930018 approved these changes

2021-05-18 16:46 UTC, merged