Pal 1025 s3 k8s config
gchq/Palisade-readers pull request #80
Opened 2021-05-21 16:33 UTC by dev930018

2021-05-26 12:33 UTC, pd104923 requested changes
A couple of questions/suggestions

2021-05-27 14:50 UTC, dev930018 commented on s3-reader/src/main/java/uk/gov/gchq/palisade/service/data/s3/S3Properties.java
> +public final class S3Properties {
Nope

2021-06-01 11:37 UTC, pd104923 requested changes
Looks good, just the license changes that need to be reverted.

2021-06-03 14:55 UTC, pd104923 submitted a review, later dismissed

2021-06-03 15:18 UTC, developer01189998819991197253 requested changes

2021-06-03 15:18 UTC, developer01189998819991197253 commented on s3-resource-service/src/main/resources/application-s3.yaml
> +  # path-style-access: false
path style access is deprecated, update!

2021-06-04 10:30 UTC, developer01189998819991197253 approved these changes

2021-06-08 13:39 UTC, pd104923 approved these changes

2021-06-08 16:11 UTC, merged