Pal 684 pd104923
gchq/Palisade-readers pull request #82
Opened 2021-06-21 12:30 UTC by pd104923

2021-06-21 13:24 UTC, m78233 commented on hadoop-data-reader/pom.xml
> +        <assertj.version>3.18.0</assertj.version>
Question on the versions.  With repos that use spring we are relying on the version that comes with Spring boot.  The version of Spring Boot is 2.3.1.RELEASE so I would have expected that the dependencies would be used here. 
 This would equate to  5.7.2 for JUnit5 and 3.19.0 for AssertJ.  Where did we get these versions from?

2021-06-21 13:44 UTC, m78233 commented on hadoop-data-reader/pom.xml
> +            <!-- JUnit, Jupiter, SpringBootTest etc... -->
Might not need the explicit dependencies depending on what you find out about the relying on Spring Boot for the dependencies.

2021-06-21 14:13 UTC, m78233 requested changes
Suggest reviewing the use of declaring JUnit5 and AssertJ in the Maven files.

2021-06-21 15:50 UTC, pd104923 commented on hadoop-data-reader/pom.xml
> +        <assertj.version>3.18.0</assertj.version>
Using Spring is not going to be viable as the readers are not set up to be Spring-boot services and therefore do not have the spring-boot-starter-parent in the parent pom like the services do.
The rest of the modules have all had to explicitly add in the unit test dependencies which is why I have added these specific version to this module.

2021-06-21 15:50 UTC, pd104923 commented on hadoop-data-reader/pom.xml
> +            <!-- JUnit, Jupiter, SpringBootTest etc... -->
Please see the response in the above comment.

2021-06-22 12:15 UTC, m78233 commented on hadoop-data-reader/pom.xml
> +        <assertj.version>3.18.0</assertj.version>
Noticed that we have a legacy artifact.  There is a S3Initaliser and S3Initalizer.  Could you remove the S3Initalizer?

2021-06-22 12:32 UTC, m78233 commented on hadoop-data-reader/pom.xml
> +        <assertj.version>3.18.0</assertj.version>
Ok, then we can revisit the topic of the version number at a later time.

2021-06-22 12:34 UTC, m78233 approved these changes
Ok covered off what we discussed.

2021-06-23 14:42 UTC, dev930018 approved these changes

2021-06-30 17:00 UTC, merged