PAL-1082 removed resource parents
gchq/Palisade-readers pull request #85
Opened 2021-07-02 14:54 UTC by dev930018

2021-07-06 08:33 UTC, pd104923 requested changes
Revert the changes in licenses/gnu_lgpl_2.1.html and licenses/mit_license.html license files. A couple of comments in the s3Builders

2021-07-06 08:33 UTC, pd104923 commented on s3-resource-service/src/main/java/uk/gov/gchq/palisade/service/resource/s3/util/S3ResourceBuilder.java
>  public class S3ResourceBuilder extends AbstractResourceBuilder {
Should this JavaDoc be the same as the data-reader builder?
```
/**
 * Builder for S3-based {@link FileResource}. Requires the URI for the S3 Resource. Use of this class is initiated by using the
 * parent class's {@code ResourceBuilder.create()} static method with a String or URI for a valid S3 Resource. This will then
 * prompt the {@code S3ResourceBuilder} to return an instance of {@code S3Resource} for the specified Resource.
 */
```

2021-07-06 08:33 UTC, pd104923 commented on s3-data-reader/src/main/java/uk/gov/gchq/palisade/service/data/s3/util/S3ResourceBuilder.java
>  public class S3ResourceBuilder extends AbstractResourceBuilder {
Can the static imports be removed from both of these builders now?

2021-07-06 08:33 UTC, pd104923 commented on s3-resource-service/src/main/java/uk/gov/gchq/palisade/service/resource/s3/util/S3ResourceBuilder.java
>  public class S3ResourceBuilder extends AbstractResourceBuilder {
Ditto here about static imports

2021-07-14 10:21 UTC, developer01189998819991197253 approved these changes

2021-07-15 08:40 UTC, merged