PAL-1086-data-reader-reactive-streams initial commit
gchq/Palisade-readers pull request #91
Opened 2021-07-14 13:40 UTC by dev930018

2021-07-21 09:11 UTC, pd104923 requested changes
A few questions and a couple of suggestions

2021-07-21 09:11 UTC, pd104923 commented on s3-resource-service/src/test/java/uk/gov/gchq/palisade/service/resource/s3/util/S3ResourceBuilderTest.java
> +                .as("Check that when building a resource with an s3 prefix, it is an instance of a S3Resource")
```suggestion
                .as("Check that when building a resource with an s3 prefix, it is an instance of a DirectoryResource")
```

2021-07-21 09:11 UTC, pd104923 commented on s3-resource-service/src/test/java/uk/gov/gchq/palisade/service/resource/s3/util/S3ResourceBuilderTest.java
> +                .as("Check that when building a resource with an s3 prefix, it is an instance of a S3Resource")
```suggestion
                .as("Check that when building a resource with an s3 prefix, it is an instance of a SystemResource")
```

2021-07-21 16:46 UTC, developer01189998819991197253 requested changes

2021-07-21 16:46 UTC, developer01189998819991197253 commented on NOTICES.md
> +* AssertJ fluent assertions ([org.assertj:assertj-core:3.19.0](https://assertj.github.io/doc/assertj-core/))
we dont need both versions of assertJ

2021-07-21 16:46 UTC, developer01189998819991197253 commented on avro-serialiser/pom.xml
> +        <assertj.version>3.19.0</assertj.version>
change to 3.18.0 like used elsewhere

2021-07-21 16:46 UTC, developer01189998819991197253 commented on hadoop-data-reader/src/test/java/uk/gov/gchq/palisade/service/data/hadoop/HadoopDataReaderTest.java
> -    void testReadTextFileWithRules() throws IOException {
Do we not want to test with and without rules?

2021-07-22 09:47 UTC, pd104923 submitted a review, later dismissed

2021-07-22 10:01 UTC, dev930018 commented on hadoop-data-reader/src/test/java/uk/gov/gchq/palisade/service/data/hadoop/HadoopDataReaderTest.java
> -    void testReadTextFileWithRules() throws IOException {
Data Readers now have nothing to do with rules, just reading data

2021-07-22 14:00 UTC, pd104923 approved these changes

2021-07-26 15:55 UTC, developer01189998819991197253 submitted a review, later dismissed

2021-07-27 13:50 UTC, developer01189998819991197253 approved these changes

2021-07-27 16:19 UTC, ac74475 approved these changes

2021-07-27 16:19 UTC, developer01189998819991197253 approved these changes

2021-07-27 16:43 UTC, merged