Pal 1095 readers readmes
gchq/Palisade-readers pull request #92
Opened 2021-07-19 10:03 UTC by developer01189998819991197253

2021-07-19 11:35 UTC, ac74475 requested changes
Just some suggested additions to improve the documentation

2021-07-19 11:35 UTC, ac74475 commented on hadoop-resource-service/README.md
> +The Hadoop Resource Service contains Hadoop specific configuration required to allow the Resource Service to communicate with Hadoop and check if resources exist.
Similar to the hadoop data service comment and expand on what the difference is between the data service one. Which is that it is for building up the metadata by directly listing the files rather than reading the data files.

2021-07-19 11:35 UTC, ac74475 commented on hadoop-resource-service/README.md
> +If the resource does exist, a `LeafResource` is created with the resourceId and connection detail information so that it can be read by the Data Service.
Does this set a default connection detail, or where does that info come from?

2021-07-19 11:35 UTC, ac74475 commented on s3-data-reader/README.md
> +
Is there any Alpakka S3 specific config that can be set and if so how?

2021-07-19 11:35 UTC, ac74475 commented on s3-resource-service/README.md
> +
Is there any Alpakka S3 specific config that can be set and if so how?

2021-07-19 11:35 UTC, ac74475 commented on hadoop-data-reader/README.md
> +
Any way to set any hadoop lib specific config and if so how?

2021-07-19 16:10 UTC, developer01189998819991197253 commented on hadoop-data-reader/README.md
> +
We could add some Map<String, String> ConfigurationProperties class and build it all into a hadoop Configuration object, but this is not yet implemented

2021-07-20 08:42 UTC, ac74475 commented on hadoop-resource-service/README.md
> +Using the Hadoop API outlined [here](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/FileSystemShell.html), and found here in [maven](https://mvnrepository.com/artifact/org.a
the resource metadata is also used by the policy service to apply the resource level policies

2021-07-20 08:43 UTC, ac74475 commented on hadoop-data-reader/README.md
> +
if you cant currently tweak that config then there is no need to add it

2021-07-20 12:48 UTC, ac74475 approved these changes

2021-07-20 14:07 UTC, dev930018 requested changes

2021-07-20 14:07 UTC, dev930018 commented on hadoop-data-reader/README.md
> +However, although Hadoop supports local File Systems and S3 Object stores, it won't be the most efficient, and other modules should be considered.
```suggestion
Although Hadoop supports local File Systems and S3 Object stores, it won't be the most efficient, and other modules should be considered.
```
Maybe also point to the data-service simple reader for local fs, and the s3 reader for s3 object stores

2021-07-20 14:07 UTC, dev930018 commented on hadoop-data-reader/README.md
> +The Hadoop Data Reader contains the Hadoop specific configuration required to allow the Data Service to read data from [Apache Hadoop](https://hadoop.apache.org/) and for Palisade to work with Hadoop
```suggestion
The Hadoop Data Reader contains the Hadoop specific classes and configuration required to allow the Data Service to read data from [Apache Hadoop](https://hadoop.apache.org/) and for Palisade to work with Hadoop deployments.  
```

2021-07-20 14:07 UTC, dev930018 commented on hadoop-data-reader/README.md
> +Using the Hadoop API outlined [here](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/FileSystemShell.html), and found here in [maven](https://mvnrepository.com/artifact/org.a
```suggestion
Using the Hadoop API outlined [here](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/FileSystemShell.html), and found [here in maven](https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-common), the Data Service can then communicate with local file systems, HDFS (Hadoop file systems) and S3 object stores.
```

2021-07-20 14:07 UTC, dev930018 commented on hadoop-resource-service/README.md
> +Using the Hadoop API outlined [here](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/FileSystemShell.html), and found here in [maven](https://mvnrepository.com/artifact/org.a
```suggestion
Using the Hadoop API outlined [here](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/FileSystemShell.html), and found [here in maven](https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-common), the Resource Service can then communicate with local file systems, HDFS (Hadoop file systems) and S3 object stores to check if the resource exists by listing the files, and then add metadata to the returned LeafResource for use within the rest of Palisade, specifically for use within the Data Service when reading resources, and the Policy Service when finding and applying resource level policies.
```

2021-07-20 14:07 UTC, dev930018 commented on hadoop-resource-service/README.md
> +```
No note on efficiency? Or are we presuming using the hadoop-resource-service on an object store like s3 (where supported by hadoop) is not going to be the real bottleneck, unlike the data-reader as warned?

2021-07-20 14:32 UTC, ac74475 approved these changes

2021-07-20 15:00 UTC, dev930018 approved these changes

2021-07-20 15:00 UTC, merged